[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors (flake8)
    "W",    # pycodestyle warnings (flake8)
    "F",    # pyflakes (flake8)
    "I",    # isort (import sorting)
    "UP",   # pyupgrade (modernize Python code)
    "B",    # flake8-bugbear (catch common bugs)
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
]

ignore = [
    "E203",  # Whitespace before ':' (conflicts with Black)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
python_version = "3.13"

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
strict_equality = true

warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
