[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.13"

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
strict_equality = true

warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
